# 
FROM python:3.9-slim

# Prevents Python from writing pyc files.
ENV PYTHONDONTWRITEBYTECODE=1

# Keeps Python from buffering stdout and stderr to avoid situations where
# the application crashes without emitting any logs due to buffering.
ENV PYTHONUNBUFFERED=1

WORKDIR /code
# 
COPY ./requirements.txt /code/requirements.txt

#RUN apk --no-cache update

RUN	pip install --no-cache-dir -r requirements.txt
